const actions = {
  USER_LOGIN:'USER_LOGIN',
  USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
  USER_LOGOUT:'USER_LOGOUT',
  // JOB ACTION
  UPLOAD_POST:'UPLOAD_POST',
  UPLOAD_POST_SUCCESS:'UPLOAD_POST_SUCCESS',
  GET_ALL_JOB:'GET_ALL_JOB',
  GET_ALL_JOB_SUCCESS:'GET_ALL_JOB_SUCCESS',
  DELETE_JOB:'DELETE_JOB',
  


}
export default actions;