const actions = {
  USER_LOGIN:'USER_LOGIN',
  USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
  USER_LOGOUT:'USER_LOGOUT',
  USER_SIGNUP:'USER_SIGNUP',
  
  // JOB ACTION
  UPLOAD_POST:'UPLOAD_POST',
  UPLOAD_POST_SUCCESS:'UPLOAD_POST_SUCCESS',
  GET_ALL_JOB:'GET_ALL_JOB',
  GET_ALL_JOB_SUCCESS:'GET_ALL_JOB_SUCCESS',
  DELETE_JOB:'DELETE_JOB',
  EDIT_JOB:'EDIT_JOB',
  EDIT_JOB_SUCCESS:'EDIT_JOB_SUCCESS',
  // GET INFO USER
  GET_USER_INFO:'GET_USER_INFO',
  GET_USER_INFO_SUCCESS:'GET_USER_INFO_SUCCESS',
  DELET_USER_INFO:'DELET_USER_INFO',
  EDIT_USER:'EDIT_USER',
  EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',


  // GET ACCOUNT
  GET_LIST_USER:'GET_LIST_USER',
  GET_LIST_USER_SUCCESS:'GET_LIST_USER_SUCCESS',
  GET_LIST_USER_REC:'GET_LIST_USER_REC',
  GET_LIST_USER_REC_SUCCESS:'GET_LIST_USER_REC_SUCCESS',
  FILTER_USER:"FILTER_USER",
  FILTER_USER_USERNAME:'FILTER_USER_USERNAME',
  // GET LIST RECRUITMENT
  GET_LIST_RECRUITMENT:'GET_LIST_RECRUITMENT',
  GET_LIST_RECRUITMENT_SUCCESS:'GET_LIST_RECRUITMENT_SUCCESS',
  // VERIFY CANDIDATE
  VERIFY_CANDIDATE:'VERIFY_CANDIDATE',
  VERIFY_CANDIDATE_SUCCESS:'VERIFY_CANDIDATE_SUCCESS',

  // FeedBack Job
  APPROVE_TO_JOB:'APPROVE_TO_JOB',
  APPROVE_TO_JOB_SUCCESS:'APPROVE_TO_JOB_SUCCESS',
  REJECT_TO_JOB:'REJECT_TO_JOB',
  REJECT_TO_JOB_SUCCESS:'REJECT_TO_JOB_SUCCESS',
  APPLY_TO_JOB:'APPLY_TO_JOB',
  APPLY_TO_JOB_SUCCESS:'APPLY_TO_JOB_SUCCESS',
  // Checkout
  ADD_COINS:'ADD_COINS',
  UPGRADE_VIP:'UPGRADE_VIP',
  REMOVE_COINS:'REMOVE_COINS'

}
export default actions;