const actions = {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  ADD_TODO_SUCCESS:'ADD_TODO_SUCCESS',
  USER_LOGIN:'USER_LOGIN',
  USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
  UPLOAD_POST:'UPLOAD_POST',
  UPLOAD_POST_SUCCESS:'UPLOAD_POST_SUCCESS',
  GET_ALL_JOB:'GET_ALL_JOB',
  GET_ALL_JOB_SUCCESS:'GET_ALL_JOB_SUCCESS',
  DELETE_JOB:'DELETE_JOB',
  // DELETE_JOB_SUCCESS:'DELETE_JOB_SUCCESS'


}
export default actions;